name = "Learn"
uuid = "7fe9aef3-13c5-4b6c-9e7d-0c7329c95c36"
authors = ["Brynjar Smári Bjarnason <binni@binnisb.com> and contributors"]
version = "0.2.0"

[deps]
BusinessDays = "4f18b42c-503e-5345-9536-bb0f25fc7038"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.5"
